# Generated by Django 6.1.1 on 2026-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='horário')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=12, verbose_name='status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
